### ISSUE TITLE
Project Task title emoji is not showing properly

### ISSUE THREAD

**Issue by heliomar-pena** [Katsu08/SOME_ISSUES_TEMPLATE#3]
**Describe the bug**
The issue name for project task is showing incorrect emoji

**To Reproduce**
1. Go to the repository
2. Click on issues
3. Click on new Issue

**Expected behavior**
Show a check emoji :white_check_mark:

**Screenshots**
![imagen](https://user-images.githubusercontent.com/66505715/136492433-64a47098-318f-42c9-b602-b00ddeb38a55.png)

**Additional context**
This emoji can change by other than can guide the user

**Comment by Israel-Laguan** [comment]
I think emoji is shown as text/string so is not parsed by Github's magic. Remember this emoji is from Github and not from Unicode, so is normal a string doesn't show it properly.

I propose not to use emoji here but inside the template, what do you think?
